import Head from 'next/head'
import io from 'socket.io-client'
import { useState, useEffect } from 'react'
import { CookiesProvider, useCookies } from 'react-cookie';
import Link from 'next/link'
import { useRouter } from 'next/router'

const socket = io("http://localhost:5000")

export default function Home() {
  const [message, setMessage] = useState("")
  const [list, setList] = useState([])
  const [users, setUsers] = useState([])
  const [currentUser, setCurrentUser] = useState("")
  const [cookies, setCookie] = useCookies(['name'])
  
  // const [username, setUsername] = useState('') 

  useEffect(() => {
    console.log(cookies.name)
    // setCurrentUser(getCookie('name'))
  }, [])

  const setCookieName = (cookieName) => {
    setCurrentUser(cookieName)
  }

  const addUser = (username) => {
    // setUsers([...users, username])
    socket.emit("send_message", { message: username })
  }

  const hundleSendMessage = () => {
    //　サーバーへ送信
    socket.emit("send_message", { message: message })
    setMessage = ("")
  }
  //サーバーから受信
  socket.on("received_message", (data) => {
    console.log(data["message"])
    setUsers([...users, data["message"]])
  })

  return (
    <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <CookiesProvider>
          <div>
            {users.map((user, i) => (
              <div key={i}>
                {user}
              </div>
            ))}
          </div>
          <div>
            あなたの名前:
            <h1 suppressHydrationWarning>
              { cookies.name }
            </h1>
          </div>
        </CookiesProvider>
    </div>
  )
}
