import Head from 'next/head'
import Image from 'next/image'
import io from 'socket.io-client'
import { useState, useEffect } from 'react'
import InputUserName from '../components/InputUserName'

const socket = io("http://localhost:5000")

export default function Home() {
  const [message, setMessage] = useState("")
  const [list, setList] = useState([])
  const [users, setUsers] = useState(['ドリップ', 'ハルク', 'ホーク'])
  // const [username, setUsername] = useState('') 

  useEffect(() => {
    // alert('Hello')
    console.log('hihi')
  }, [])

  const addUser = (username) => {
    setUsers([...users, username])
    // setUsername('')
  }

  // const nameChange = (e) => {
  //   setUsername(() => e.target.value)
  // }

  const hundleSendMessage = () => {
    //　サーバーへ送信
    socket.emit("send_message", { message: message })
    setMessage = ("")
  }
  //サーバーから受信
  socket.on("received_message", (data) => {
    console.log(data)
    setList([...list, data])
  })

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className='text-2xl text-indigo-500'>表示名を入力してください</h1>
        <InputUserName
          addUser={addUser}
        />
        {users.map((user, i) => (
          <div key={i}>
            {user}
          </div>
        ))}
      </div>
    </div>
  )
}
